name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        resolver:
        #- nightly
        - lts-20
        - lts-19
        - lts-18

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            mkdir -p ../_newstack
            #stack upgrade --force-download --local-bin-path ../_newstack
            #../_newstack/stack --version
            #../_newstack/stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
            stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
